#!/bin/bash

# Move to the directory where this script is
cdir=$( dirname $0 )

sudo rm -f rootfs_lxc_ubuntu64-ostack-controller rootfs_lxc_ubuntu64-ostack-compute rootfs_lxc_ubuntu64-ostack-network

if [ "$1" == "cfgd" ]; then
    sudo ln -s vnx_rootfs_lxc_ubuntu64-22.04-v025-openstack-controller-cfgd rootfs_lxc_ubuntu64-ostack-controller
else
    sudo ln -s vnx_rootfs_lxc_ubuntu64-22.04-v025-openstack rootfs_lxc_ubuntu64-ostack-controller
fi

sudo ln -s vnx_rootfs_lxc_ubuntu64-22.04-v025-openstack rootfs_lxc_ubuntu64-ostack-compute
sudo ln -s vnx_rootfs_lxc_ubuntu64-22.04-v025-openstack rootfs_lxc_ubuntu64-ostack-network
